// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PregnantWeb.Data;

#nullable disable

namespace PregnantWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905192649_AddCourseLessons")]
    partial class AddCourseLessons
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PregnantWeb.Models.Blog", b =>
                {
                    b.Property<string>("BlogId")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DoctorFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            BlogId = "1",
                            Content = "Sample blog content.",
                            Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorFullName = "Dr. Nino Beridze",
                            Title = "Sample blog title",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJRuWFdumlIeB3qvtAKUpUh7MEnyoJQlODKPMpSZMh2A&s=10"
                        },
                        new
                        {
                            BlogId = "2",
                            Content = "Sample blog content.",
                            Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorFullName = "Dr. sia dolidze",
                            Title = "Sample blog title",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdAHYzOSCfysHMgI9tjWaLz4AjkkEDFl0gYt3uTqktcQ&s=10"
                        });
                });

            modelBuilder.Entity("PregnantWeb.Models.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkingHours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContactInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "თბილისი, ლუბლიანას ქ. 5, Mikheil Chiaureli Ln, Tbilisi",
                            Email = "contact@example.com",
                            MobileNumber = "+995 555 00 00 00",
                            WorkingHours = "Mon-Fri 09:00-18:00"
                        });
                });

            modelBuilder.Entity("PregnantWeb.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("PregnantWeb.Models.CourseLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Chapter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CourseLessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Chapter = "intro",
                            Duration = "05:30",
                            SectionId = 1,
                            SectionName = "who_am_i",
                            Title = "ვინ ვარ",
                            TypeId = 1,
                            Url = "https://www.youtube.com/embed/jNQXAC9IVRw?rel=0&modestbranding=1"
                        },
                        new
                        {
                            Id = 2,
                            Chapter = "intro",
                            Duration = "04:10",
                            SectionId = 2,
                            SectionName = "what_you_will_learn",
                            Title = "რას შეისწავლი",
                            TypeId = 1,
                            Url = "https://www.youtube.com/embed/9bZkp7q19f0?rel=0&modestbranding=1"
                        },
                        new
                        {
                            Id = 3,
                            Chapter = "childNutrition",
                            Duration = "08:20",
                            SectionId = 1,
                            SectionName = "breastfeeding",
                            Title = "ძუძუთი კვება",
                            TypeId = 1,
                            Url = "https://www.youtube.com/embed/kJQP7kiw5Fk?rel=0&modestbranding=1"
                        },
                        new
                        {
                            Id = 4,
                            Chapter = "childNutrition",
                            Duration = "07:15",
                            SectionId = 2,
                            SectionName = "bottle_feeding",
                            Title = "ხელოვნური კვება",
                            TypeId = 1,
                            Url = "https://www.youtube.com/embed/dQw4w9WgXcQ?rel=0&modestbranding=1"
                        });
                });

            modelBuilder.Entity("PregnantWeb.Models.CoursePromoSummary", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LessonQty")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CourseId");

                    b.ToTable("Promo");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseName = "ორსულთა ონლაინ სკოლა",
                            Description = "9 ვიდეო გაკვეთილი ორსულობის და მშობიარობის შესახებ. 📌დამატებითი მასალა ფაილების სახით. 📌მუდმივი კავშირი ჩემთან-გამოცდილ მეან—გინეკოლოგთან-სადაც ამომწურავად აგიხსნით თქვენთვის საინტერესო საკითხებს. 📌ხშირად დასმული შეკითხვები და პასუხები.",
                            LessonQty = 9,
                            Price = 120m,
                            Title = "ვემზადებით მშობიარობისთვის",
                            VideoUrl = "https://www.youtube.com/embed/dQw4w9WgXcQ?rel=0&modestbranding=1"
                        },
                        new
                        {
                            CourseId = 2,
                            CourseName = "ორსულობისთვის მომზადება-გზამკვლევი",
                            Description = "ორსულობისთვის მომზადება ექიმთან ერთად : ონლაინ ლექციები..📍ვისთვის არის ეს ლექციები? 📍ეს ლექციები შენთვისაა: 📌თუ გეგმავ ორსულობას უახლოეს 3–12 თვეში 📌გინდა ექიმის მიერ მოწოდებული ინფორმაცია 📌 გსურს მშვიდად და გააზრებულად დაიწყო ორსულობა . ❌ ვებინარი არ არის მათთვის, ვინც უკვე ორსულად არის და ეძებს ორსულობის მართვის ინფორმაციას. 📝 რა შედის? სრული აღწერილობისთვის ეწვიეთ ჩემს ინსტაგრამ გვერდს ან მომწერეთ პირადში.",
                            LessonQty = 1,
                            Price = 50m,
                            Title = "პრეგრავიდარული მომზადება-გზა ბედნიერი დედობისაკენ",
                            VideoUrl = "https://www.youtube.com/embed/y8Ja-m_4rHk?rel=0&modestbranding=1"
                        });
                });

            modelBuilder.Entity("PregnantWeb.Models.RegisterOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RegisterOrders");
                });

            modelBuilder.Entity("PregnantWeb.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
